### PR TITLE
Add button

### PR DESCRIPTION
**Pull request by oguzkarademir**
Guys! I think this solution is not useful, but yesterday I worked long time on this and found a solution 🤔 . This project is more about `DOM` and I am not so good right now, I hope it's enough, please review my solution

### CODE REVIEW

**Review by pavelbidenko2018 — APPROVED** [review]
Hi @oguzkarademir !
You can try to use the method ```insertAdjacentHTML()``` instead of a bunch of recursive ```append()```.
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

**Review by Sayed94h — COMMENTED** [review]
Hi @oguzkarademir , I reviewed your PR but I did not understand. Did you use something to store the data in the locale storage so that when users close the browser then the data will not go away?

Greetings, 
Sayed

**Review by okozmovskaya — COMMENTED** [review]
Oguz, I didn't understand script and can't help you, but on my screen the button doesn't work  - just flash my entered task and then disappear

**Comment by oguzkarademir** [comment]
Guys! I'll get over it @pavelbidenko2018 @Sayed94h @okozmovskaya 👍

**Pull request closed without merging**
