### PR TITLE
Completed done-button

### PR DESCRIPTION
**Pull request by okozmovskaya**
Closes # 5.

Guys, I did my button, but it works only for the first items, may be do you have some idea why - I don't understand.

### CODE REVIEW

**Review by Sayed94h — APPROVED** [review]
Hi @okozmovskaya , I reviewed your PR. It looks okay but there are many questions in general, like: where do you store the data?, where do you call the handler function?, ... 

Greetings, Sayed

**Comment by okozmovskaya** [comment]
> Hi @okozmovskaya , I reviewed your PR. It looks okay but there are many questions in general, like: where do you store the data?, where do you call the handler function?, ...
> 
> Greetings, Sayed

Hi, @Sayed94h There is the string of html-code in the file show-list.js. You find your button (fa-fa...) and add onclick-properties.

**Review by pavelbidenko2018 — COMMENTED** [review]
Hi @okozmovskaya !
The problem is that  the method 'let item = document.querySelector('.item');' finds only the first tag within the document (https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector).
So, when you click "done" button for the first time - style of item is changed OK. 
But when clicking for the 2nd time - it finds the same item, which is already 'done'

**Comment by okozmovskaya** [comment]
> Hi @okozmovskaya !
> The problem is that the method 'let item = document.querySelector('.item');' finds only the first tag within the document (https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector).
> So, when you click "done" button for the first time - style of item is changed OK.
> But when clicking for the 2nd time - it finds the same item, which is already 'done'

Thank you, @pavelbidenko2018 !)) You are right. Now it works, but in my version there is need click two times)) Please, merge my PR

**Pull request merged**
